name: Workflow B

on:
  workflow_run:
    workflows: ["Workflow A"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Display Input Parameters
        run: |
          echo "appID: ${{ needs.Workflow A.outputs.appID }}"
          echo "suiteName: ${{ needs.Workflow A.outputs.suiteName }}"
      
      # Add your Workflow B steps here using the appID and suiteName variables
