name: Workflow B

on:
  workflow_run:
    workflows: ["Workflow A"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Display Input Parameters
        run: |
          echo "appID: "
          echo "suiteName:"

      # Add your workflow B steps here using the appID and suiteName variables
