name: Build and Deploy with Cypress

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Docker Build and Deploy on Private Server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: Uurnik Systems
          username: rehan.khan
          key: .i#aiZyZg]9V!bF
          script: |
            git pull origin main  # Pull latest changes
            sudo docker-compose down
            sudo docker-compose up -d --build
            echo "Docker build and deployment completed"

  cypress-tests:
    needs: build-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Cypress
        run: npm install cypress

      - name: Run Cypress Tests
        run: npx cypress run
